### ISSUE TITLE
Web UI: Img2Img no longer working after dagf2101-main branch merge

### ISSUE THREAD

**Issue by namion** [lstein/stable-diffusion#165]
When using img2img in the web UI, the process starts and it decodes the image but it throws an error:

Request to generate with prompt: dog
Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s]sampler 'k_lms' is not yet supported. Using DDM sampler
loaded input image of size (512, 512) from ./img2img-tmp.png
Running DDIM Sampling with 37 timesteps
Decoding image: 100%|██████████████████████████████████████████████████████████████████| 37/37 [00:09<00:00,  3.79it/s]
Generating: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.61s/it]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 6871)
Traceback (most recent call last):
  File "C:\Users\Matt\.conda\envs\ldm2\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Matt\.conda\envs\ldm2\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Matt\.conda\envs\ldm2\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Matt\.conda\envs\ldm2\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\Matt\.conda\envs\ldm2\lib\http\server.py", line 415, in handle_one_request
    method()
  File "w:\ai art\stable-diffusion\ldm\dream\server.py", line 67, in do_POST
    outputs = self.model.img2img(prompt,
  File "w:\ai art\stable-diffusion\ldm\simplet2i.py", line 191, in img2img
    return self.prompt2png(prompt, outdir, **kwargs)
  File "w:\ai art\stable-diffusion\ldm\simplet2i.py", line 172, in prompt2png
    results = self.prompt2image(prompt, **kwargs)
  File "w:\ai art\stable-diffusion\ldm\simplet2i.py", line 315, in prompt2image
    if upscale is not None or gfpgan_strength > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by cvar66** [comment]
Just ran into the same problem, identical same error

**Comment by theRolento** [comment]
Same error

**Comment by lstein** [comment]
Could you try running "conva env update -f environment.yaml" ??

I am actually finding a different bug in which the image file load fails with **PIL.UnidentifiedImageError: cannot identify image file './img2img-tmp.png**. Oddly, the exact same img2img arguments are working at the command line.

**Comment by lstein** [comment]
Ok, I solved my problem (due to unclosed filehandle on slow filesystem). Now able to reproduce the original problem and am working on it. There will be a commit to a new bugfixes branch RSN.

**Comment by lstein** [comment]
Checkout the new "bugfixes" branch and this will start working again. GFPGAN is working correctly on the web server, but upscaling is not yet implemented. I will likely add this later today.
