### ISSUE TITLE
Missed two places where PngWriter's __init__() signature changed

### ISSUE THREAD

**Issue by xaroth8088** [lstein/stable-diffusion#236]
@lstein This appears to be related to recent work removing the `batch_size` parameter from `PngWriter`, and is just two spots that were missed (lines 91 and 134).

```
Exception happened during processing of request from ('127.0.0.1', 57222)
Traceback (most recent call last):
  File "/home/xaroth/anaconda3/envs/lstein-ldm/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/xaroth/anaconda3/envs/lstein-ldm/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/xaroth/anaconda3/envs/lstein-ldm/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/xaroth/anaconda3/envs/lstein-ldm/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/xaroth/anaconda3/envs/lstein-ldm/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/xaroth/lstein-stable-diffusion/stable-diffusion/ldm/dream/server.py", line 91, in do_POST
    pngwriter = PngWriter(
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by bakkot** [comment]
https://github.com/lstein/stable-diffusion/pull/231 should fix this.
