### ISSUE TITLE
Error loading module. Only CUDA backend is supported

### ISSUE THREAD

**Issue by sibernewf** [lstein/stable-diffusion#238]
I have been setting this up in Ubuntu 22 in a Virtualbox Vm.

I have followed the instructions as indicated, except for the part to get the weights.  Instead I curled them as below:
	curl https://www.googleapis.com/storage/v1/b/aai-blog-files/o/sd-v1-4.ckpt?alt=media > sd-v1-4.ckpt

when i try: python3 scripts/dream.py  (or with the -l extension), I receive the following output:

Error loading model.  Only the CUDA backend is supported
Traceback (most recent call last):
  File "/home/alan/stable-diffusion/ldm/simplet2i.py", line 536, in load_model
      self.device = self._get_device()
 File "/home/alan/stable-diffusion/ldm/simplet2i.py", line 527, in _get_device
      device_type = choose_torch_device()
 File "/home/alan/stable-diffusion/ldm/dream/devices.py", line 7, in choose_torch_device
     if torch.backends.mps.is_available():
AttributeError: module 'torch.backends' has no attribute 'mps'

Any Ideas?

**Comment by sibernewf** [comment]
Forgot to mention after seeing the CUDA error, I installed:

sudo apt install nvidia-cuda-toolkit

**Comment by magnusviri** [comment]
This:

`elif(torch.backends.mps.is_available()):`

needs to be changed to this:

`elif hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():`

If I'm faster than the others I'll actually get this pushed before someone else.

**Comment by magnusviri** [comment]
I guess everyone is asleep!
