### ISSUE TITLE
[BUG] WEB UI: Error occurred while generating.

### ISSUE THREAD

**Issue by LipcaCZ** [lstein/stable-diffusion#249]
Hi,

I updated to the latest version while ago, but generating over web server does not work in this version - it gives me error "Error occurred while generating."

This is what's in the console:

> Exception happened during processing of request from ('127.0.0.1', 5156)
Traceback (most recent call last):
  File "C:\Users\libor\anaconda3\envs\ldm\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\libor\anaconda3\envs\ldm\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\libor\anaconda3\envs\ldm\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\libor\anaconda3\envs\ldm\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\libor\anaconda3\envs\ldm\lib\http\server.py", line 415, in handle_one_request
    method()
  File "c:\users\libor\stable-diffusion\ldm\dream\server.py", line 91, in do_POST
    pngwriter = PngWriter(
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given
----------------------------------------

Generating over command line works normally.

**Comment by jay2001** [comment]
I am getting this exact same behaviour (except my paths are different of course).

**Comment by JohanManders** [comment]
Quickfix is removing the  ```, 1``` at the end of line 92 of server.py, so lines 91-93 read:

```
        pngwriter = PngWriter(
            "./outputs/img-samples/", config['prompt']
        )
```

And remove ```, 2``` from line 134 so that it reads:

```
        step_writer = PngWriter('./outputs/intermediates/', prompt)
```

**Comment by lstein** [comment]
This is fixed in current main. Sorry for the delay in getting the fix pushed out.
