### ISSUE TITLE
Issues when running the `dream.py` script on M1 mac: `AttributeError: module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats'`

### ISSUE THREAD

**Issue by ALenfant** [lstein/stable-diffusion#250]
Hello!

First of all, thanks for all the hard work!

I'm seeing the following error when trying to use the `dream.py` script:
```
$ python scripts/dream.py

* Initializing, be patient...

Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Setting Sampler to k_lms
model loaded in 5.91s

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> Lolcat
Traceback (most recent call last):
  File "/Users/antonin.lenfant/PERSONNEL/stable-diffusion/scripts/dream.py", line 518, in <module>
    main()
  File "/Users/antonin.lenfant/PERSONNEL/stable-diffusion/scripts/dream.py", line 99, in main
    main_loop(t2i, opt.outdir, opt.prompt_as_dir, cmd_parser, infile)
  File "/Users/antonin.lenfant/PERSONNEL/stable-diffusion/scripts/dream.py", line 208, in main_loop
    image_list  = t2i.prompt2image(image_callback=callback, **vars(opt))
  File "/Users/antonin.lenfant/PERSONNEL/stable-diffusion/ldm/simplet2i.py", line 283, in prompt2image
    torch.cuda.torch.cuda.reset_peak_memory_stats()
  File "/opt/homebrew/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/cuda/memory.py", line 260, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
AttributeError: module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats'
```

The weird thing is that it doesn't appear when calling the original `txt2img.py` script like this
```
python scripts/orig_scripts/txt2img.py --prompt "lolcat"
```
It works fine and I get the expected output.

My guess is that we're calling a CUDA-specific method (`cuda.reset_peak_memory_stats()`) on a non-CUDA device but I'm not very familiar with ML.

Thanks for the work and the help!

**Comment by lstein** [comment]
I can fix that. It's just related to reporting memory statistics. I'll disable it when not running on a CUDA system.
