### ISSUE TITLE
Error launching dream.py

### ISSUE THREAD

**Issue by summersonne** [lstein/stable-diffusion#259]
python scripts\dream.py -l
* Initializing, be patient...

Loading model from models/ldm/text2img-large/model.ckpt
Traceback (most recent call last):
  File "scripts\dream.py", line 535, in <module>
    main()
  File "scripts\dream.py", line 86, in main
    t2i.load_model()
  File "c:\users\myuser\stable-diffusion\ldm\simplet2i.py", line 538, in load_model
    model = self._load_model_from_config(config, self.weights)
  File "c:\users\myuser\stable-diffusion\ldm\simplet2i.py", line 590, in _load_model_from_config
    model = instantiate_from_config(config.model)
  File "c:\users\myuser\stable-diffusion\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
TypeError: __init__() missing 1 required positional argument: 'personalization_config'

**Comment by YosAwed** [comment]
Same here....

**Comment by lstein** [comment]
I suspect this is fixed in the recent release.
