### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by satputeamit** [lstein/stable-diffusion#559]
Hello everyone,
I am getting the following error please guide me.
**system configuration(laptop):**
```
RAM: 16GB
GPU: RTX 3060 - 6GB (laptop)
1TB SSD
Processor: Ryzen 7 - 5800 - 8 cores

```

I followed all steps for installing stable-diffusion which is mentioned in the readme and the setup is done without any error. 
After that, I run **python scripts\preload_models.py**
output:
```
preloading bert tokenizer...
...success
preloading Kornia requirements (ignore the deprecation warnings)...
...success
preloading CLIP model (Ignore the deprecation warnings)...


...success
Loading models from RealESRGAN and facexlib
...success
```

After that is run **python scripts\dream.py**
output:
```
* Initializing, be patient...

>> cuda not available, using device cpu
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Model loaded in 21.80s
>> Setting Sampler to k_lms

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
```

And when i type text and hit enter following error occurs:
```
dream> cat play with ball
Traceback (most recent call last):
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\generate.py", line 303, in prompt2image
    uc, c = get_uc_and_c(
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\dream\conditioning.py", line 16, in get_uc_and_c
    uc = model.get_learned_conditioning([''])
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\models\diffusion\ddpm.py", line 828, in get_learned_conditioning
    c = self.cond_stage_model.encode(
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\modules\encoders\modules.py", line 455, in encode
    return self(text, **kwargs)
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\modules\encoders\modules.py", line 450, in forward
    z = self.transformer(input_ids=tokens, **kwargs)
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\modules\encoders\modules.py", line 420, in transformer_forward
    return self.text_model(
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\modules\encoders\modules.py", line 393, in text_encoder_forward
    last_hidden_state = self.encoder(
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\stable-diffusion-main\stable-diffusion-main\ldm\modules\encoders\modules.py", line 320, in encoder_forward
    layer_outputs = encoder_layer(
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\ldm\lib\site-packages\transformers\models\clip\modeling_clip.py", line 316, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\normalization.py", line 189, in forward
    return F.layer_norm(
  File "D:\anaconda3\envs\ldm\lib\site-packages\torch\nn\functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 0.64s
Outputs:

```

**Comment by lstein** [comment]
This is likely an issue on some video cards which we are actively working on. To work around it, try starting dream.py with **--full_precision**. Please come back and leave a comment letting us know whether this did or did not fix the problem.

**Comment by satputeamit** [comment]
Hi @lstein ,
Now it is working with **--full_precision**.
Thank you very much.

**Comment by gibron** [comment]
For posterity and gratitude, I experienced this issue and using `full_precision` ie, `python3 scripts/dream.py --full_precision --web` worked for me as well.

I am on an Apple M1 Pro with the Apple GPU.

**Comment by Bacon-Tech** [comment]
I do not appear to have that dream.py file...
