### ISSUE TITLE
Windows - It breaks after 'dream'

### ISSUE THREAD

**Issue by HQuasar** [lstein/stable-diffusion#6]
I followed the Windows installation guide and up until executing the 'dream' command all was fine. I also moved the contents of the 'scripts' folder to the main folder as suggested.

There's a small mistake in the guide, the pre-release weight folder should be named "text2img-large" instead of "text2img.large", since it keeps raising an exception 'no such file or directory' if I name it "text2img.large".

Anyway, after invoking "dream.py -l" for the first time, the initialization is successful. After inputting a simple prompt, however, I get this:

* Initialization done! Awaiting your command (-h for help, q to quit)...
dream> an astronaut riding a horse
Traceback (most recent call last):
  File "C:\Users\xxx\stable-diffusion\dream.py", line 276, in <module>
    main()
  File "C:\Users\xxx\stable-diffusion\dream.py", line 67, in main
    main_loop(t2i,cmd_parser,log)
  File "C:\Users\xxx\stable-diffusion\dream.py", line 114, in main_loop
    results = t2i.txt2img(**vars(opt))
  File "C:\Users\xxx\stable-diffusion\ldm\simplet2i.py", line 154, in txt2img
    model = self.load_model()  # will instantiate the model or return it from cache
  File "C:\Users\xxx\stable-diffusion\ldm\simplet2i.py", line 375, in load_model
    config = OmegaConf.load(self.config)
  File "C:\Users\xxx\Conda\envs\ldm\lib\site-packages\omegaconf\omegaconf.py", line 183, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\configs\\latent-diffusion\\txt2img-1p4B-eval.yaml'

I tried creating the folder (and the .yaml file) myself. I get this error now:

* Initialization done! Awaiting your command (-h for help, q to quit)...
dream> an astronaut riding a horse
Loading model from models/ldm/text2img-large/model.ckpt
Traceback (most recent call last):
  File "C:\Users\xxx\stable-diffusion\dream.py", line 276, in <module>
    main()
  File "C:\Users\xxx\stable-diffusion\dream.py", line 67, in main
    main_loop(t2i,cmd_parser,log)
  File "C:\Users\xxx\stable-diffusion\dream.py", line 114, in main_loop
    results = t2i.txt2img(**vars(opt))
  File "C:\Users\xxx\stable-diffusion\ldm\simplet2i.py", line 154, in txt2img
    model = self.load_model()  # will instantiate the model or return it from cache
  File "C:\Users\xxx\stable-diffusion\ldm\simplet2i.py", line 377, in load_model
    model = self._load_model_from_config(config,self.weights)
  File "C:\Users\xxx\stable-diffusion\ldm\simplet2i.py", line 396, in _load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "C:\Users\xxx\Conda\envs\ldm\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\xxx\Conda\envs\ldm\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\xxx\Conda\envs\ldm\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/ldm/text2img-large/model.ckpt'

even though such folder (and file) exists.

**Comment by lstein** [comment]
I think the issue is that the files are identified using relative directory paths. When you launch the script, make sure your current directory is the same one that main.py and the subdirectories scripts, ldm, and models are in. Try "python scripts\dream.py -l"

**Comment by lstein** [comment]
I'm glad you figured it out. I'll tweak the README to make it easier for people to follow.
