### ISSUE TITLE
After running python scripts\dream.py -l I get this error:

### ISSUE THREAD

**Issue by V4r0m4st3r** [lstein/stable-diffusion#7]
* Initializing, be patient...

Traceback (most recent call last):
  File "scripts\dream.py", line 276, in <module>
    main()
  File "scripts\dream.py", line 37, in main
    from pytorch_lightning import logging
  File "C:\Users\louis\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "C:\Users\louis\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "C:\Users\louis\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "C:\Users\louis\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "C:\Users\louis\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\metrics\utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (C:\Users\louis\anaconda3\envs\ldm\lib\site-packages\torchmetrics\utilities\data.py)

**Comment by lstein** [comment]
Try this:
```
conda activate ldm
pip3 install torchmetrics==0.6.0
```

**Comment by lstein** [comment]
Did it work?

**Comment by V4r0m4st3r** [comment]
Yes, it fixed the issue. But after that I realized I use an amd gpu so it won't work anyways lol...> Did it work?

**Comment by lstein** [comment]
Bummer!
