### ISSUE TITLE
Issue with pytorch when running textual inversion 

### ISSUE THREAD

**Issue by Bored-Anarchist** [lstein/stable-diffusion#700]
After solving the first issue with OmegaConf (which was solved by proper spacing of the prompt), I came across this while trying to run main.py for textual inversion. I skipped the first parts of it initializing here due to the amount of text.
```
Restored from ./models/ldm/stable-diffusion-v1/model.ckpt with 0 missing and 2 unexpected keys
Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Monitoring val/loss_simple_ema as checkpoint metric.
Merged modelckpt-cfg:
{'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs\\my_cat2022-09-19T10-13-27_my_cat\\checkpoints', 'filename': '{epoch:06}', 'verbose': True, 'save_last': True, 'monitor': 'val/loss_simple_ema', 'save_top_k': 1, 'every_n_train_steps': 500}}
Traceback (most recent call last):
  File "./main.py", line 870, in <module>
    trainer = Trainer.from_argparse_args(trainer_opt, **trainer_kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\properties.py", line 421, in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 52, in from_argparse_args
    return cls(**trainer_kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\connectors\env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 346, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1251, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\utilities\device_parser.py", line 84, in parse_gpu_ids
    gpus = _normalize_parse_gpu_string_input(gpus)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\utilities\device_parser.py", line 132, in _normalize_parse_gpu_string_input
    return [int(x.strip()) for x in s.split(",") if len(x) > 0]
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\utilities\device_parser.py", line 132, in <listcomp>
    return [int(x.strip()) for x in s.split(",") if len(x) > 0]
ValueError: invalid literal for int() with base 10: '\\'
```
Tried fixing the spacing again but did not work.  Any suggestions to fix? Thanks.

**Comment by Bored-Anarchist** [comment]
Solved
