### ISSUE TITLE
When running textual inversion, gloo is not found as a valid distributed type.

### ISSUE THREAD

**Issue by Bored-Anarchist** [lstein/stable-diffusion#701]
With the enviroment variable set to gloo and line 699 in main.py set to gloo as well, I receive the error that gloo is not a valid DistributedType.
```
trainer_config['accelerator'] = 'gloo' (line 699)
```
Error:
```
Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Monitoring val/loss_simple_ema as checkpoint metric.
Merged modelckpt-cfg:
{'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs\\my_cat2022-09-19T10-47-25_nmy_cat\\checkpoints', 'filename': '{epoch:06}', 'verbose': True, 'save_last': True, 'monitor': 'val/loss_simple_ema', 'save_top_k': 1, 'every_n_train_steps': 500}}
ValueError: 'gloo' is not a valid DistributedType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 868, in <module>
    trainer = Trainer.from_argparse_args(trainer_opt, **trainer_kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\properties.py", line 421, in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 52, in from_argparse_args
    return cls(**trainer_kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\connectors\env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 354, in __init__
    self.accelerator_connector = AcceleratorConnector(
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py", line 152, in __init__
    self.set_distributed_mode()
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py", line 776, in set_distributed_mode
    self._distrib_type = DistributedType(self.distributed_backend)
  File "C:\Users\x\.conda\envs\ldm\lib\enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\x\.conda\envs\ldm\lib\enum.py", line 600, in __new__
    raise exc
  File "C:\Users\x\.conda\envs\ldm\lib\enum.py", line 584, in __new__
    result = cls._missing_(value)
  File "C:\Users\x\.conda\envs\ldm\lib\enum.py", line 613, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'gloo' is not a valid DistributedType
```
Any way to solve this? Thanks.

**Comment by Bored-Anarchist** [comment]
Solved
