### ISSUE TITLE
error when trying to run img to img when using  --init_img

### ISSUE THREAD

**Issue by dansand182** [lstein/stable-diffusion#78]
here is the stacktrace i got from it 

Oops! A runtime error has occurred. If this is unexpected, please copy-and-paste this stack trace and post it as an Issue to http://github.com/lstein/stable-diffusion
Traceback (most recent call last):
  File "c:\dev\repos\stable-diffusion\ldm\simplet2i.py", line 390, in img2img
    samples = sampler.decode(z_enc, c, t_enc, unconditional_guidance_scale=cfg_scale,
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\dev\repos\stable-diffusion\ldm\models\diffusion\ddim.py", line 239, in decode
    x_dec, _ = self.p_sample_ddim(x_dec, cond, ts, index=index, use_original_steps=use_original_steps,
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\dev\repos\stable-diffusion\ldm\models\diffusion\ddim.py", line 178, in p_sample_ddim
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "c:\dev\repos\stable-diffusion\ldm\models\diffusion\ddpm.py", line 1028, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\dev\repos\stable-diffusion\ldm\models\diffusion\ddpm.py", line 1485, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\dev\repos\stable-diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 736, in forward
    h = th.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 6 but got size 5 for tensor number 1 in the list.

**Comment by lstein** [comment]
This can happen when the init_img isn't exactly 512x512. Could this be the case?

I will write code to produce a more comprehensible error message.

**Comment by lstein** [comment]
Would you mind providing the exact prompt you used? Maybe there is a conflict between the file's size and the requested width and height.

**Comment by GiusTex** [comment]
A similar problem happened to me (RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 18 but got size 17 for tensor number 1 in the list.). My prompt was: ""anime visual of a girl, photorealistic, fan art, HD" --init_img=./init-images/Valorie.png --strength=0.5 -s100 -n1      and the image size was 399x563. Tomorrow i will try to change the size in photoshop to 512x512. The accepted sizes are only 512x512 or others too?

**Comment by TruongQuocTruong** [comment]
I have a similar problem when I try to generate an image in the IMG2IMG task. It works with my input image of size (512, 346), in spite of not having size (512x512).  But when I try to some another size (512, 372); (508, 677); (300, 512);... It has an error: "  RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 10 but got size 9 for tensor number 1 in the list."
I appreciate it if someone supports me to fix it! Thank alot
